FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt -y update && apt -y upgrade && apt -y install python3-pip && apt install -y python3.10-venv


## For devcontainer, persists bash history

